# Generated by Django 5.2 on 2025-05-01 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rutinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio'),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='rutinas.RutinaEjercicio', to='rutinas.ejercicio'),
        ),
        migrations.AddField(
            model_name='sesionejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio'),
        ),
        migrations.AddField(
            model_name='sesionejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina'),
        ),
        migrations.AddField(
            model_name='sesionejercicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rutinaejercicio',
            unique_together={('rutina', 'ejercicio', 'orden')},
        ),
    ]
